### PR TITLE
Add link to live demo

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by fjsnogueira** [comment]
It could be just https://teamofone.github.io/psc16-team3 instead, its shorter and more future proof, because once the sharing via URL is in place the query parameters may chance.

**Comment by waldyrious** [comment]
Yes, but the link is masked, so that isn't a big deal, and besides at the moment the raw url takes people to the playlist page, which is confusing. We can always update it once we change the landing page of the app :)

**Comment by fjsnogueira** [comment]
Once we implement any logic for some of the features described in the issues we have the url will stop working (the part from the hash tag to the right) , as example: if we implement server or client side creation or retrieval of the songs (besides de URL sharing). the issue of the URL taking to the playlist page can be changed.

**Comment by waldyrious** [comment]
Shall we start by changing the start page, then? I don't think it's good for our landing page to be something unexpected and with no relation to current functionality of the app. At the moment the only way to avoid it is if we add a custom URL like this, but if we make it so that going directly to the unhashed URL shows the chords page immediately, we can then change the readme link to point to the root URL.

**Comment by fjsnogueira** [comment]
I've started working on changing the start page and working on related issue #30 , the start page is working fine, so we may merge this branch just for the start page, and I can iterate in it creating a new one to finish issue #30.

**Comment by waldyrious** [comment]
Sure. So the idea is merging this, and then changing the URL to the main one once #30 is merged, did I read that right? In that case, I'd need someone's approval for this PR.

**Review by fjsnogueira — APPROVED** [review]
Good for now

**Pull request merged**
